
import java.awt.Color;
import javax.swing.border.MatteBorder;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author rafae
 */
public class HeroPanel extends javax.swing.JPanel {

    private String hero;
    
    /**
     * Creates new form HeroPanel
     */
    public HeroPanel(String hero) {
        this.hero = hero;
       
        initComponents();
        heroLabel.setText(hero);
        this.setBorder(new MatteBorder(
                        0, 0, 1, 0, Color.decode(ThemeColors.BLUE_COLOR)));
    }

    
    public String getHero() {
        return hero;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        heroLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(45, 54, 76));

        heroLabel.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        heroLabel.setForeground(new java.awt.Color(255, 255, 255));
        heroLabel.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(heroLabel)
                .addContainerGap(350, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(heroLabel)
                .addContainerGap(276, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel heroLabel;
    // End of variables declaration//GEN-END:variables
}
